First PR
Sehun-Kim/IndianPoker_JAVA_RE pull request #1
Opened 2019-01-10 07:29 UTC by Sehun-Kim

## gradle 빌드로 변경하였습니다.
다시 부탁드립니다!

2019-01-10 07:49 UTC, javajigi requested changes
구현 잘 했네요. 👍 
피드백 좀 남겼어요.

2019-01-10 07:49 UTC, javajigi commented on src/main/java/indianpoker/domain/Dealer.java
> +    public GameResultDto judgeGameWinner(Player player1, Player player2) {
`GameResultDto result = player1.judge(player2);` 구조가 더 낫지 않을까?

2019-01-10 07:49 UTC, javajigi commented on src/main/java/indianpoker/domain/Dealer.java
> +        if (player1.showChips().isEmpty() || player2.showChips().isEmpty())
`player1.isGameOver() || player2.isGameOver()`는 어떨까?

2019-01-10 07:49 UTC, javajigi commented on src/main/java/indianpoker/domain/Turn.java
> +    public static Turn of() {
기본 생성자만 가지는데 굳이 정적 팩토리 메소드 필요한가?

2019-01-10 07:49 UTC, javajigi commented on src/main/java/indianpoker/vo/Chips.java
> +    private static final String TEN_CHIP = "💰";
convention 위반??
상수 값이 먼저 위치해야함.

2019-01-10 07:49 UTC, javajigi commented on src/main/java/support/domain/Deck.java
> +        this.deck = this.shuffle(this.init());
이와 같이 구현할 경우 Deck을 테스트하기 어렵지 않을까?
Deck이 테스트  가능한 구조로 변경해 본다.

2019-01-10 07:49 UTC, javajigi commented on src/main/java/support/domain/Deck.java
> +    public List<Card> shuffle(List<Card> cards) {
이 메소드는 private으로 구현해도 되지 않나?

2019-01-10 07:49 UTC, javajigi commented on src/test/java/IndianPokerTest.java
> +public class IndianPokerTest {
이 테스트는 뭐하러 만들었음???

2019-01-14 05:39 UTC, Sehun-Kim commented on src/main/java/indianpoker/domain/Dealer.java
> +    public GameResultDto judgeGameWinner(Player player1, Player player2) {
`Player`가 `Card`를 가지지 않고 `Dealer`가 `Card`를 가지는 것이 게임 흐름 상 맞다고 생각하여 위와 같이 구현하였습니다.

2019-01-14 05:40 UTC, Sehun-Kim commented on src/test/java/IndianPokerTest.java
> +public class IndianPokerTest {
TestCase를 정리하는 용도로 만든 더미 Test입니다. 피드백 반영하여 삭제하였습니다.

2019-01-14 05:51 UTC, merged